# Information Retrieval in High Dimensional Data
## Lab #1, 19.10.2017

## NumPy Basics

### Task 1
In this task, we will familiarize ourselves with some basic NumPy functionalites.
Make sure that it is imported to your IPython shell.

In [3]:
import numpy as np

a) Generate an arbitrary one-dimensional array n with n.shape=(8,) and display it 

In [10]:
n = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype='float64')
print(n)

[ 1.  2.  3.  4.  5.  6.  7.  8.]


b) Create a new array n_odd which consists of the odd entries of n. Display it.

In [12]:
n_odd = n[::2]
print(n_odd)

[ 1.  3.  5.  7.]


c) Create an new array n_rev which contains the entries of n in reverse order.
Display it.

In [22]:
n_rev = np.flipud(n)
print(n_rev)

[ 8.  7.  6.  5.  4.  3.  2.  1.]


What would be the output of the following code

    import numpy as np
    a = np.array([1, 2, 3, 4, 5])
    b = a[1:4]
    b[0] = 200
    print(a[1])

In [24]:
import numpy as np
a = np.array ([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


$ \rightarrow $ The slice is passed by reference

e) Create a two-dimensional array called m with m.shape=(3, 4) and display it.

In [25]:
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


f) Create another array m_revrowel which contains the same elements as m, but with reversed rows. Display it.

In [27]:
m_revrowel = np.fliplr(m)
print(m_revrowel)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


g) Create yet another array m_revall which contains the same elements as m, but with reversed rows and columns. Display it.

In [28]:
m_revall = np.flipud(m_revrowel)
print(m_revall)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


h) Create an array m_cut which contains only the elements from the first and last rows and columns of m. Display it.

In [29]:
m_cut = m[0::2,0::3]
print(m_cut)

[[ 1  4]
 [ 9 12]]
